### ISSUE TITLE
Missing dataset name in test split path in data.yaml

### ISSUE THREAD

**Issue by maxsitt** [roboflow/notebooks#82]
### Search before asking

- [X] I have searched the Roboflow Notebooks [issues](https://github.com/roboflow-ai/notebooks/issues) and found no similar bug report.

### Notebook name

[YOLOv5 PyTorch Object Detection](https://colab.research.google.com/github/roboflow-ai/notebooks/blob/main/notebooks/train-yolov5-object-detection-on-custom-data.ipynb)

### Bug

When using the Roboflow data import, the dataset name is not written to the path of the dataset test split in the `data.yaml` file.

Example:

```
test: ../test/images
train: dataset_name/train/images
val: dataset_name/valid/images
```

This can lead to problems, e.g. when trying to validate on the dataset test split (with `--task test`):

```
FileNotFoundError: test: /content/yolov5/test/images does not exist
```

It is no problem adding the dataset name to the test path in the `data.yaml` file, but an inexperienced user might not know how to do this.

I don't know if there is a reason behind not adding the dataset name to the test path, if not this might be a bug.

### Environment

- Google Colab
- OS: Ubuntu 20.04.5 LTS (Focal Fossa)
- Python: 3.9.16
- roboflow 0.2.34
- YOLOv5 v7.0-120-g3e55763

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment]
Hi, @maxsitt! Could you send me the link to your dataset on Roboflow?

**Comment by maxsitt** [comment]
Hi @SkalskiP!

Sure, here is the link: [Roboflow dataset](https://universe.roboflow.com/maximilian-sittinger/insect_detect_detection/dataset/7)

Thanks for looking into it!

**Comment by SkalskiP** [comment]
Hi, @maxsitt I just tested, and the download works as expected. Training as well. 

I used this code to download your dataset:

```
%cd /content/yolov5
from roboflow import Roboflow
rf = Roboflow(api_key="API_KEY")
project = rf.workspace("maximilian-sittinger").project("insect_detect_detection")
dataset = project.version(7).download("yolov5")
``` 

When I take a look at `data.yaml` it looks like this:

```
names:
- insect
nc: 1
roboflow:
  license: CC BY 4.0
  project: insect_detect_detection
  url: https://universe.roboflow.com/maximilian-sittinger/insect_detect_detection/dataset/7
  version: 7
  workspace: maximilian-sittinger
test: ../test/images
train: Insect_Detect_detection-7/train/images
val: Insect_Detect_detection-7/valid/images
```
